In [1]:
import pandas as pd

In [3]:
data = pd.read_csv("data.csv")

In [4]:
data.head()

  Reported_Date                 HA Sex Age_Group Classification_Reported
0    2020-01-26      Out of Canada   M     40-49           Lab-diagnosed
1    2020-02-02  Vancouver Coastal   F     50-59           Lab-diagnosed
2    2020-02-05      Out of Canada   F     20-29           Lab-diagnosed
3    2020-02-05      Out of Canada   M     30-39           Lab-diagnosed
4    2020-02-11           Interior   F     30-39           Lab-diagnosed

In [5]:
data

     Reported_Date                 HA Sex Age_Group Classification_Reported
0       2020-01-26      Out of Canada   M     40-49           Lab-diagnosed
1       2020-02-02  Vancouver Coastal   F     50-59           Lab-diagnosed
2       2020-02-05      Out of Canada   F     20-29           Lab-diagnosed
3       2020-02-05      Out of Canada   M     30-39           Lab-diagnosed
4       2020-02-11           Interior   F     30-39           Lab-diagnosed
...            ...                ...  ..       ...                     ...
3414    2020-07-23             Fraser   M     20-29           Lab-diagnosed
3415    2020-07-23           Interior   M     60-69           Lab-diagnosed
3416    2020-07-23           Interior   M     40-49           Lab-diagnosed
3417    2020-07-23           Northern   F     70-79           Lab-diagnosed
3418    2020-07-23  Vancouver Coastal   M     60-69           Lab-diagnosed

[3419 rows x 5 columns]