In [150]:
#import necessory file 
import pandas as pd 
import numpy as np
import datetime
from datetime import datetime

In [151]:
#import data
data = pd.read_csv("WhatsApp Chat with PDD.DA’19.txt", error_bad_lines=False)

b'Skipping line 71: expected 2 fields, saw 3\nSkipping line 99: expected 2 fields, saw 3\nSkipping line 100: expected 2 fields, saw 3\nSkipping line 119: expected 2 fields, saw 3\nSkipping line 135: expected 2 fields, saw 3\nSkipping line 155: expected 2 fields, saw 3\nSkipping line 156: expected 2 fields, saw 3\nSkipping line 174: expected 2 fields, saw 3\nSkipping line 211: expected 2 fields, saw 3\nSkipping line 213: expected 2 fields, saw 3\nSkipping line 215: expected 2 fields, saw 3\nSkipping line 217: expected 2 fields, saw 3\nSkipping line 218: expected 2 fields, saw 3\nSkipping line 223: expected 2 fields, saw 3\nSkipping line 225: expected 2 fields, saw 3\nSkipping line 227: expected 2 fields, saw 3\nSkipping line 228: expected 2 fields, saw 3\nSkipping line 229: expected 2 fields, saw 3\nSkipping line 230: expected 2 fields, saw 3\nSkipping line 232: expected 2 fields, saw 3\nSkipping line 238: expected 2 fields, saw 3\nSkipping line 239: expected 2 fields, saw 3\nSkipping line 241: expected 2 fields, saw 3\nSkipping line 257: expected 2 fields, saw 3\nSkipping line 306: expected 2 fields, saw 3\nSkipping line 313: expected 2 fields, saw 3\nSkipping line 333: expected 2 fields, saw 3\nSkipping line 334: expected 2 fields, saw 3\nSkipping line 336: expected 2 fields, saw 3\nSkipping line 337: expected 2 fields, saw 3\nSkipping line 373: expected 2 fields, saw 4\nSkipping line 384: expected 2 fields, saw 3\nSkipping line 390: expected 2 fields, saw 3\nSkipping line 393: expected 2 fields, saw 3\nSkipping line 398: expected 2 fields, saw 3\nSkipping line 401: expected 2 fields, saw 3\nSkipping line 418: expected 2 fields, saw 3\nSkipping line 438: expected 2 fields, saw 3\nSkipping line 440: expected 2 fields, saw 3\nSkipping line 445: expected 2 fields, saw 3\nSkipping line 450: expected 2 fields, saw 3\nSkipping line 472: expected 2 fields, saw 3\nSkipping line 474: expected 2 fields, saw 3\nSkipping line 477: expected 2 fields, saw 3\nSkipping line 504: expected 2 fields, saw 3\nSkipping line 560: expected 2 fields, saw 3\nSkipping line 581: expected 2 fields, saw 3\nSkipping line 594: expected 2 fields, saw 3\nSkipping line 595: expected 2 fields, saw 4\nSkipping line 641: expected 2 fields, saw 3\nSkipping line 669: expected 2 fields, saw 3\nSkipping line 676: expected 2 fields, saw 3\nSkipping line 690: expected 2 fields, saw 3\nSkipping line 698: expected 2 fields, saw 3\nSkipping line 713: expected 2 fields, saw 3\nSkipping line 734: expected 2 fields, saw 3\nSkipping line 746: expected 2 fields, saw 3\nSkipping line 748: expected 2 fields, saw 3\nSkipping line 772: expected 2 fields, saw 3\nSkipping line 786: expected 2 fields, saw 3\nSkipping line 788: expected 2 fields, saw 3\nSkipping line 812: expected 2 fields, saw 3\nSkipping line 813: expected 2 fields, saw 3\nSkipping line 814: expected 2 fields, saw 3\nSkipping line 839: expected 2 fields, saw 3\nSkipping line 841: expected 2 fields, saw 3\nSkipping line 845: expected 2 fields, saw 3\nSkipping line 850: expected 2 fields, saw 3\nSkipping line 890: expected 2 fields, saw 4\nSkipping line 910: expected 2 fields, saw 3\nSkipping line 914: expected 2 fields, saw 3\nSkipping line 962: expected 2 fields, saw 4\nSkipping line 989: expected 2 fields, saw 3\nSkipping line 990: expected 2 fields, saw 3\nSkipping line 1004: expected 2 fields, saw 3\nSkipping line 1016: expected 2 fields, saw 3\nSkipping line 1018: expected 2 fields, saw 3\nSkipping line 1023: expected 2 fields, saw 3\nSkipping line 1031: expected 2 fields, saw 3\nSkipping line 1083: expected 2 fields, saw 3\nSkipping line 1090: expected 2 fields, saw 3\nSkipping line 1092: expected 2 fields, saw 3\nSkipping line 1106: expected 2 fields, saw 3\nSkipping line 1143: expected 2 fields, saw 3\nSkipping line 1147: expected 2 fields, saw 4\nSkipping line 1174: expected 2 fields, saw 3\nSkipping line 1180: expected 2 fields, saw 3\nSkipping line 1185: expected 2 fields, saw 3\nSkipping line 1191: expected 2 fields, saw 3\nSkipping line 1196: expected 2 fields, saw 4\nSkipping line 1216: expected 2 fields, saw 3\nSkipping line 1254: expected 2 fields, saw 3\nSkipping line 1264: expected 2 fields, saw 3\nSkipping line 1268: expected 2 fields, saw 3\nSkipping line 1284: expected 2 fields, saw 3\nSkipping line 1290: expected 2 fields, saw 4\nSkipping line 1291: expected 2 fields, saw 4\nSkipping line 1310: expected 2 fields, saw 3\nSkipping line 1319: expected 2 fields, saw 4\nSkipping line 1329: expected 2 fields, saw 3\nSkipping line 1337: expected 2 fields, saw 3\nSkipping line 1344: expected 2 fields, saw 3\nSkipping line 1369: expected 2 fields, saw 3\nSkipping line 1390: expected 2 fields, saw 3\nSkipping line 1395: expected 2 fields, saw 3\nSkipping line 1412: expected 2 fields, saw 3\nSkipping line 1413: expected 2 fields, saw 3\nSkipping line 1417: expected 2 fields, saw 3\nSkipping line 1421: expected 2 fields, saw 3\nSkipping line 1422: expected 2 fields, saw 3\nSkipping line 1423: expected 2 fields, saw 3\nSkipping line 1430: expected 2 fields, saw 3\nSkipping line 1432: expected 2 fields, saw 3\nSkipping line 1433: expected 2 fields, saw 3\nSkipping line 1452: expected 2 fields, saw 3\nSkipping line 1453: expected 2 fields, saw 3\nSkipping line 1454: expected 2 fields, saw 3\nSkipping line 1455: expected 2 fields, saw 3\nSkipping line 1456: expected 2 fields, saw 3\nSkipping line 1457: expected 2 fields, saw 3\nSkipping line 1458: expected 2 fields, saw 3\nSkipping line 1480: expected 2 fields, saw 3\nSkipping line 1482: expected 2 fields, saw 3\nSkipping line 1503: expected 2 fields, saw 3\nSkipping line 1510: expected 2 fields, saw 3\nSkipping line 1581: expected 2 fields, saw 4\nSkipping line 1591: expected 2 fields, saw 3\nSkipping line 1601: expected 2 fields, saw 3\nSkipping line 1602: expected 2 fields, saw 3\nSkipping line 1620: expected 2 fields, saw 3\nSkipping line 1630: expected 2 fields, saw 3\nSkipping line 1634: expected 2 fields, saw 3\nSkipping line 1651: expected 2 fields, saw 3\nSkipping line 1663: expected 2 fields, saw 4\nSkipping line 1682: expected 2 fields, saw 3\nSkipping line 1689: expected 2 fields, saw 3\nSkipping line 1693: expected 2 fields, saw 4\nSkipping line 1724: expected 2 fields, saw 3\nSkipping line 1747: expected 2 fields, saw 3\nSkipping line 1775: expected 2 fields, saw 3\nSkipping line 1779: expected 2 fields, saw 3\nSkipping line 1832: expected 2 fields, saw 3\nSkipping line 1847: expected 2 fields, saw 3\nSkipping line 1904: expected 2 fields, saw 3\nSkipping line 1905: expected 2 fields, saw 3\nSkipping line 1911: expected 2 fields, saw 3\nSkipping line 1926: expected 2 fields, saw 3\nSkipping line 1934: expected 2 fields, saw 3\nSkipping line 1936: expected 2 fields, saw 3\nSkipping line 1948: expected 2 fields, saw 3\nSkipping line 1954: expected 2 fields, saw 3\nSkipping line 1970: expected 2 fields, saw 4\nSkipping line 1973: expected 2 fields, saw 4\nSkipping line 1976: expected 2 fields, saw 4\nSkipping line 1979: expected 2 fields, saw 4\nSkipping line 1980: expected 2 fields, saw 4\nSkipping line 1981: expected 2 fields, saw 3\nSkipping line 1987: expected 2 fields, saw 3\nSkipping line 1990: expected 2 fields, saw 3\nSkipping line 1995: expected 2 fields, saw 4\nSkipping line 1996: expected 2 fields, saw 3\nSkipping line 1997: expected 2 fields, saw 6\nSkipping line 1999: expected 2 fields, saw 4\nSkipping line 2000: expected 2 fields, saw 3\nSkipping line 2012: expected 2 fields, saw 4\nSkipping line 2015: expected 2 fields, saw 3\nSkipping line 2016: expected 2 fields, saw 3\nSkipping line 2019: expected 2 fields, saw 3\nSkipping line 2060: expected 2 fields, saw 3\nSkipping line 2082: expected 2 fields, saw 3\nSkipping line 2096: expected 2 fields, saw 3\nSkipping line 2102: expected 2 fields, saw 4\nSkipping line 2104: expected 2 fields, saw 3\nSkipping line 2114: expected 2 fields, saw 3\nSkipping line 2121: expected 2 fields, saw 3\nSkipping line 2125: expected 2 fields, saw 3\nSkipping line 2135: expected 2 fields, saw 3\nSkipping line 2139: expected 2 fields, saw 3\nSkipping line 2184: expected 2 fields, saw 3\nSkipping line 2319: expected 2 fields, saw 4\nSkipping line 2323: expected 2 fields, saw 3\nSkipping line 2333: expected 2 fields, saw 3\nSkipping line 2335: expected 2 fields, saw 3\nSkipping line 2341: expected 2 fields, saw 3\nSkipping line 2344: expected 2 fields, saw 5\nSkipping line 2354: expected 2 fields, saw 4\nSkipping line 2367: expected 2 fields, saw 3\nSkipping line 2375: expected 2 fields, saw 5\nSkipping line 2387: expected 2 fields, saw 3\nSkipping line 2396: expected 2 fields, saw 3\nSkipping line 2397: expected 2 fields, saw 3\nSkipping line 2431: expected 2 fields, saw 4\nSkipping line 2442: expected 2 fields, saw 3\nSkipping line 2457: expected 2 fields, saw 3\nSkipping line 2466: expected 2 fields, saw 3\nSkipping line 2477: expected 2 fields, saw 3\nSkipping line 2481: expected 2 fields, saw 3\nSkipping line 2504: expected 2 fields, saw 4\nSkipping line 2540: expected 2 fields, saw 3\nSkipping line 2548: expected 2 fields, saw 3\nSkipping line 2557: expected 2 fields, saw 3\nSkipping line 2565: expected 2 fields, saw 4\nSkipping line 2566: expected 2 fields, saw 3\nSkipping line 2636: expected 2 fields, saw 3\nSkipping line 2642: expected 2 fields, saw 3\nSkipping line 2645: expected 2 fields, saw 3\nSkipping line 2672: expected 2 fields, saw 3\nSkipping line 2699: expected 2 fields, saw 3\nSkipping line 2718: expected 2 fields, saw 3\nSkipping line 2720: expected 2 fields, saw 3\nSkipping line 2721: expected 2 fields, saw 3\nSkipping line 2723: expected 2 fields, saw 4\nSkipping line 2741: expected 2 fields, saw 3\nSkipping line 2745: expected 2 fields, saw 3\nSkipping line 2748: expected 2 fields, saw 3\nSkipping line 2749: expected 2 fields, saw 3\nSkipping line 2768: expected 2 fields, saw 3\nSkipping line 2807: expected 2 fields, saw 3\nSkipping line 2861: expected 2 fields, saw 3\nSkipping line 2899: expected 2 fields, saw 3\nSkipping line 2907: expected 2 fields, saw 3\nSkipping line 2911: expected 2 fields, saw 3\nSkipping line 2930: expected 2 fields, saw 4\nSkipping line 2936: expected 2 fields, saw 3\nSkipping line 2943: expected 2 fields, saw 3\nSkipping line 2987: expected 2 fields, saw 3\nSkipping line 2990: expected 2 fields, saw 3\nSkipping line 2998: expected 2 fields, saw 4\nSkipping line 3003: expected 2 fields, saw 3\nSkipping line 3004: expected 2 fields, saw 6\nSkipping line 3005: expected 2 fields, saw 3\nSkipping line 3013: expected 2 fields, saw 3\nSkipping line 3029: expected 2 fields, saw 3\nSkipping line 3040: expected 2 fields, saw 3\nSkipping line 3064: expected 2 fields, saw 3\nSkipping line 3095: expected 2 fields, saw 3\nSkipping line 3110: expected 2 fields, saw 3\nSkipping line 3141: expected 2 fields, saw 3\nSkipping line 3149: expected 2 fields, saw 4\nSkipping line 3153: expected 2 fields, saw 3\nSkipping line 3211: expected 2 fields, saw 3\nSkipping line 3251: expected 2 fields, saw 3\nSkipping line 3259: expected 2 fields, saw 3\nSkipping line 3272: expected 2 fields, saw 4\nSkipping line 3291: expected 2 fields, saw 3\nSkipping line 3294: expected 2 fields, saw 4\nSkipping line 3296: expected 2 fields, saw 3\nSkipping line 3299: expected 2 fields, saw 4\nSkipping line 3300: expected 2 fields, saw 3\nSkipping line 3304: expected 2 fields, saw 3\nSkipping line 3310: expected 2 fields, saw 3\nSkipping line 3313: expected 2 fields, saw 3\nSkipping line 3328: expected 2 fields, saw 4\nSkipping line 3340: expected 2 fields, saw 3\nSkipping line 3345: expected 2 fields, saw 3\nSkipping line 3368: expected 2 fields, saw 3\nSkipping line 3449: expected 2 fields, saw 3\nSkipping line 3469: expected 2 fields, saw 3\nSkipping line 3479: expected 2 fields, saw 3\nSkipping line 3513: expected 2 fields, saw 3\nSkipping line 3519: expected 2 fields, saw 3\nSkipping line 3524: expected 2 fields, saw 3\nSkipping line 3549: expected 2 fields, saw 3\nSkipping line 3551: expected 2 fields, saw 3\nSkipping line 3574: expected 2 fields, saw 3\nSkipping line 3681: expected 2 fields, saw 3\nSkipping line 3693: expected 2 fields, saw 3\nSkipping line 3729: expected 2 fields, saw 4\nSkipping line 3759: expected 2 fields, saw 3\nSkipping line 3789: expected 2 fields, saw 3\nSkipping line 3791: expected 2 fields, saw 7\nSkipping line 3799: expected 2 fields, saw 3\nSkipping line 3803: expected 2 fields, saw 3\nSkipping line 3805: expected 2 fields, saw 3\nSkipping line 3807: expected 2 fields, saw 3\nSkipping line 3810: expected 2 fields, saw 3\nSkipping line 3863: expected 2 fields, saw 3\nSkipping line 3870: expected 2 fields, saw 3\nSkipping line 3877: expected 2 fields, saw 3\nSkipping line 3882: expected 2 fields, saw 3\nSkipping line 3903: expected 2 fields, saw 3\nSkipping line 3906: expected 2 fields, saw 3\nSkipping line 3908: expected 2 fields, saw 3\nSkipping line 3931: expected 2 fields, saw 3\nSkipping line 3942: expected 2 fields, saw 3\nSkipping line 3944: expected 2 fields, saw 3\nSkipping line 3978: expected 2 fields, saw 4\nSkipping line 3998: expected 2 fields, saw 3\nSkipping line 4006: expected 2 fields, saw 3\nSkipping line 4009: expected 2 fields, saw 3\nSkipping line 4020: expected 2 fields, saw 3\nSkipping line 4021: expected 2 fields, saw 3\nSkipping line 4033: expected 2 fields, saw 5\nSkipping line 4035: expected 2 fields, saw 3\nSkipping line 4039: expected 2 fields, saw 4\nSkipping line 4044: expected 2 fields, saw 3\nSkipping line 4064: expected 2 fields, saw 3\nSkipping line 4070: expected 2 fields, saw 3\nSkipping line 4081: expected 2 fields, saw 3\nSkipping line 4083: expected 2 fields, saw 3\nSkipping line 4086: expected 2 fields, saw 4\nSkipping line 4103: expected 2 fields, saw 3\nSkipping line 4118: expected 2 fields, saw 3\nSkipping line 4157: expected 2 fields, saw 3\nSkipping line 4177: expected 2 fields, saw 3\nSkipping line 4211: expected 2 fields, saw 3\nSkipping line 4223: expected 2 fields, saw 3\nSkipping line 4235: expected 2 fields, saw 3\nSkipping line 4238: expected 2 fields, saw 3\nSkipping line 4252: expected 2 fields, saw 3\nSkipping line 4268: expected 2 fields, saw 3\nSkipping line 4274: expected 2 fields, saw 3\nSkipping line 4290: expected 2 fields, saw 3\nSkipping line 4295: expected 2 fields, saw 4\nSkipping line 4304: expected 2 fields, saw 3\nSkipping line 4308: expected 2 fields, saw 3\nSkipping line 4311: expected 2 fields, saw 4\nSkipping line 4316: expected 2 fields, saw 3\nSkipping line 4397: expected 2 fields, saw 3\nSkipping line 4398: expected 2 fields, saw 3\nSkipping line 4399: expected 2 fields, saw 3\nSkipping line 4411: expected 2 fields, saw 3\nSkipping line 4415: expected 2 fields, saw 3\nSkipping line 4425: expected 2 fields, saw 5\nSkipping line 4448: expected 2 fields, saw 3\nSkipping line 4490: expected 2 fields, saw 3\nSkipping line 4507: expected 2 fields, saw 3\nSkipping line 4530: expected 2 fields, saw 4\nSkipping line 4544: expected 2 fields, saw 3\nSkipping line 4590: expected 2 fields, saw 3\nSkipping line 4594: expected 2 fields, saw 4\nSkipping line 4597: expected 2 fields, saw 3\nSkipping line 4618: expected 2 fields, saw 3\nSkipping line 4644: expected 2 fields, saw 3\nSkipping line 4652: expected 2 fields, saw 3\nSkipping line 4663: expected 2 fields, saw 3\nSkipping line 4686: expected 2 fields, saw 3\nSkipping line 4689: expected 2 fields, saw 3\nSkipping line 4728: expected 2 fields, saw 3\nSkipping line 4740: expected 2 fields, saw 4\nSkipping line 4796: expected 2 fields, saw 3\nSkipping line 4815: expected 2 fields, saw 3\nSkipping line 4826: expected 2 fields, saw 3\nSkipping line 4865: expected 2 fields, saw 3\nSkipping line 4891: expected 2 fields, saw 3\nSkipping line 4977: expected 2 fields, saw 5\nSkipping line 5023: expected 2 fields, saw 3\nSkipping line 5027: expected 2 fields, saw 3\nSkipping line 5068: expected 2 fields, saw 3\nSkipping line 5074: expected 2 fields, saw 4\nSkipping line 5075: expected 2 fields, saw 3\nSkipping line 5076: expected 2 fields, saw 3\nSkipping line 5102: expected 2 fields, saw 3\nSkipping line 5152: expected 2 fields, saw 3\nSkipping line 5259: expected 2 fields, saw 3\nSkipping line 5260: expected 2 fields, saw 3\nSkipping line 5270: expected 2 fields, saw 3\nSkipping line 5276: expected 2 fields, saw 3\nSkipping line 5280: expected 2 fields, saw 3\nSkipping line 5298: expected 2 fields, saw 3\nSkipping line 5349: expected 2 fields, saw 3\nSkipping line 5352: expected 2 fields, saw 3\nSkipping line 5353: expected 2 fields, saw 3\nSkipping line 5427: expected 2 fields, saw 3\nSkipping line 5444: expected 2 fields, saw 3\nSkipping line 5448: expected 2 fields, saw 3\nSkipping line 5449: expected 2 fields, saw 3\nSkipping line 5487: expected 2 fields, saw 4\nSkipping line 5488: expected 2 fields, saw 3\nSkipping line 5515: expected 2 fields, saw 3\nSkipping line 5529: expected 2 fields, saw 3\nSkipping line 5535: expected 2 fields, saw 3\nSkipping line 5554: expected 2 fields, saw 4\nSkipping line 5555: expected 2 fields, saw 3\nSkipping line 5561: expected 2 fields, saw 3\nSkipping line 5572: expected 2 fields, saw 3\nSkipping line 5578: expected 2 fields, saw 3\nSkipping line 5589: expected 2 fields, saw 3\nSkipping line 5600: expected 2 fields, saw 3\nSkipping line 5633: expected 2 fields, saw 3\nSkipping line 5638: expected 2 fields, saw 3\nSkipping line 5641: expected 2 fields, saw 3\nSkipping line 5644: expected 2 fields, saw 3\nSkipping line 5655: expected 2 fields, saw 4\nSkipping line 5661: expected 2 fields, saw 3\nSkipping line 5665: expected 2 fields, saw 3\nSkipping line 5671: expected 2 fields, saw 3\nSkipping line 5705: expected 2 fields, saw 3\nSkipping line 5722: expected 2 fields, saw 6\nSkipping line 5730: expected 2 fields, saw 3\nSkipping line 5757: expected 2 fields, saw 11\nSkipping line 5778: expected 2 fields, saw 6\nSkipping line 5789: expected 2 fields, saw 3\nSkipping line 5796: expected 2 fields, saw 3\nSkipping line 5843: expected 2 fields, saw 3\nSkipping line 5877: expected 2 fields, saw 4\nSkipping line 5891: expected 2 fields, saw 3\nSkipping line 5893: expected 2 fields, saw 3\nSkipping line 5894: expected 2 fields, saw 3\nSkipping line 5909: expected 2 fields, saw 3\nSkipping line 5919: expected 2 fields, saw 3\nSkipping line 5921: expected 2 fields, saw 3\nSkipping line 5924: expected 2 fields, saw 3\nSkipping line 5934: expected 2 fields, saw 3\nSkipping line 5953: expected 2 fields, saw 3\nSkipping line 5958: expected 2 fields, saw 3\nSkipping line 5964: expected 2 fields, saw 4\nSkipping line 5994: expected 2 fields, saw 3\nSkipping line 5999: expected 2 fields, saw 3\nSkipping line 6024: expected 2 fields, saw 3\nSkipping line 6039: expected 2 fields, saw 3\nSkipping line 6040: expected 2 fields, saw 3\nSkipping line 6043: expected 2 fields, saw 3\nSkipping line 6056: expected 2 fields, saw 4\nSkipping line 6128: expected 2 fields, saw 3\nSkipping line 6171: expected 2 fields, saw 3\nSkipping line 6174: expected 2 fields, saw 5\nSkipping line 6175: expected 2 fields, saw 3\nSkipping line 6196: expected 2 fields, saw 3\nSkipping line 6228: expected 2 fields, saw 3\nSkipping line 6231: expected 2 fields, saw 3\nSkipping line 6236: expected 2 fields, saw 4\nSkipping line 6238: expected 2 fields, saw 3\nSkipping line 6245: expected 2 fields, saw 3\nSkipping line 6246: expected 2 fields, saw 3\nSkipping line 6252: expected 2 fields, saw 3\nSkipping line 6257: expected 2 fields, saw 4\nSkipping line 6260: expected 2 fields, saw 3\nSkipping line 6263: expected 2 fields, saw 3\nSkipping line 6270: expected 2 fields, saw 3\nSkipping line 6274: expected 2 fields, saw 3\nSkipping line 6283: expected 2 fields, saw 4\nSkipping line 6284: expected 2 fields, saw 3\nSkipping line 6286: expected 2 fields, saw 3\nSkipping line 6287: expected 2 fields, saw 3\nSkipping line 6296: expected 2 fields, saw 4\nSkipping line 630

In [152]:
data

,9/4/19,5:46 PM - Messages to this group are now secured with end-to-end encryption. Tap for more info.
0,9/3/19,"5:34 PM - +91 98888 26051 created group ""Lang..."
1,9/4/19,5:46 PM - Nikita Batra DA added you
2,9/4/19,5:59 PM - +91 90414 65914 added Vasu DA Lanagara
3,9/4/19,8:21 PM - jaspreet singh: <Media omitted>
4,9/4/19,8:22 PM - jaspreet singh: Hardware required f...
...,...,...
12673,6/24/20,7:19 PM - jaspreet singh: <Media omitted>
12674,6/24/20,7:40 PM - David Vazquez Data Analytics: Does ...
12675,6/24/20,7:40 PM - jaspreet singh: no idea
12676,6/24/20,7:43 PM - Vasu DA Lanagara: Send me the Code ...
12677,6/24/20,8:08 PM - Kiran DA: Hi guys need php laravel ...

In [153]:
data.columns

Index(['9/4/19', ' 5:46 PM - Messages to this group are now secured with end-to-end encryption. Tap for more info.'], dtype='object')

In [154]:
data.rename(columns = {"9/4/19":"Date"," 5:46 PM - Messages to this group are now secured with end-to-end encryption. Tap for more info.":"info"}, inplace = True)

In [155]:
data.head()

     Date                                               info
0  9/3/19   5:34 PM - +91 98888 26051 created group "Lang...
1  9/4/19                5:46 PM - Nikita Batra DA added you
2  9/4/19   5:59 PM - +91 90414 65914 added Vasu DA Lanagara
3  9/4/19          8:21 PM - jaspreet singh: <Media omitted>
4  9/4/19   8:22 PM - jaspreet singh: Hardware required f...

In [156]:

  
# new data frame with split value columns 
new = data["info"].str.split("-", n = 1, expand = True) 
  
# making separate first name column from new data frame 
data["Time"]= new[0] 
  
# making separate last name column from new data frame 
data["Message"]= new[1] 
  
# Dropping old Name columns 
data.drop(columns =["info"], inplace = True) 
  
# df display 
data

          Date       Time                                            Message
0       9/3/19   5:34 PM     +91 98888 26051 created group "Langara College"
1       9/4/19   5:46 PM                           Nikita Batra DA added you
2       9/4/19   5:59 PM              +91 90414 65914 added Vasu DA Lanagara
3       9/4/19   8:21 PM                     jaspreet singh: <Media omitted>
4       9/4/19   8:22 PM    jaspreet singh: Hardware required for this co...
...        ...        ...                                                ...
12673  6/24/20   7:19 PM                     jaspreet singh: <Media omitted>
12674  6/24/20   7:40 PM    David Vazquez Data Analytics: Does it include...
12675  6/24/20   7:40 PM                             jaspreet singh: no idea
12676  6/24/20   7:43 PM    Vasu DA Lanagara: Send me the Code if slider ...
12677  6/24/20   8:08 PM    Kiran DA: Hi guys need php laravel developer ...

[12678 rows x 3 columns]

In [157]:

  
# new data frame with split value columns 
new = data["Message"].str.split(":", n = 1, expand = True) 
  
# making separate first name column from new data frame 
data["Name"]= new[0] 
  
# making separate last name column from new data frame 
data["Messages"]= new[1] 
  
# Dropping old Name columns 
data.drop(columns =["Message"], inplace = True) 
  
# df display 
data

,Date,Time,Name,Messages
0,9/3/19,5:34 PM,"+91 98888 26051 created group ""Langara College""",None
1,9/4/19,5:46 PM,Nikita Batra DA added you,None
2,9/4/19,5:59 PM,+91 90414 65914 added Vasu DA Lanagara,None
3,9/4/19,8:21 PM,jaspreet singh,<Media omitted>
4,9/4/19,8:22 PM,jaspreet singh,Hardware required for this course is not that...
...,...,...,...,...
12673,6/24/20,7:19 PM,jaspreet singh,<Media omitted>
12674,6/24/20,7:40 PM,David Vazquez Data Analytics,Does it include de bokeh slider? 😛
12675,6/24/20,7:40 PM,jaspreet singh,no idea
12676,6/24/20,7:43 PM,Vasu DA Lanagara,Send me the Code if slider includes😂
12677,6/24/20,8:08 PM,Kiran DA,Hi guys need php laravel developer and html d...

In [158]:
#drop NA
data.dropna(inplace =True)

In [159]:
#check unique students
data["Name"].nunique()

30

In [175]:
#counts of Names
sum(data["Name"].value_counts())

11837

In [161]:
#checking nUlls 
data.isnull().sum().sum()

0

In [162]:
data['Date'] =  pd.to_datetime(data['Date'], format='%m/%d/%y')

In [163]:
data['Date']

3       2019-09-04
4       2019-09-04
5       2019-09-04
6       2019-09-04
7       2019-09-05
           ...
12673   2020-06-24
12674   2020-06-24
12675   2020-06-24
12676   2020-06-24
12677   2020-06-24
Name: Date, Length: 11837, dtype: datetime64[ns]

In [164]:
data['Weekdays'] = data['Date'].dt.day_name()

In [165]:
data

,Date,Time,Name,Messages,Weekdays
3,2019-09-04,8:21 PM,jaspreet singh,<Media omitted>,Wednesday
4,2019-09-04,8:22 PM,jaspreet singh,Hardware required for this course is not that...,Wednesday
5,2019-09-04,8:22 PM,jaspreet singh,May be our older system work for this course,Wednesday
6,2019-09-04,8:27 PM,Dharun Canada DA,👀,Wednesday
7,2019-09-05,12:34 PM,jaspreet singh,Did anyone know where this Maths Test will be...,Thursday
...,...,...,...,...,...
12673,2020-06-24,7:19 PM,jaspreet singh,<Media omitted>,Wednesday
12674,2020-06-24,7:40 PM,David Vazquez Data Analytics,Does it include de bokeh slider? 😛,Wednesday
12675,2020-06-24,7:40 PM,jaspreet singh,no idea,Wednesday
12676,2020-06-24,7:43 PM,Vasu DA Lanagara,Send me the Code if slider includes😂,Wednesday
12677,2020-06-24,8:08 PM,Kiran DA,Hi guys need php laravel developer and html d...,Wednesday

In [166]:
temp = data

In [167]:
temp

,Date,Time,Name,Messages,Weekdays
3,2019-09-04,8:21 PM,jaspreet singh,<Media omitted>,Wednesday
4,2019-09-04,8:22 PM,jaspreet singh,Hardware required for this course is not that...,Wednesday
5,2019-09-04,8:22 PM,jaspreet singh,May be our older system work for this course,Wednesday
6,2019-09-04,8:27 PM,Dharun Canada DA,👀,Wednesday
7,2019-09-05,12:34 PM,jaspreet singh,Did anyone know where this Maths Test will be...,Thursday
...,...,...,...,...,...
12673,2020-06-24,7:19 PM,jaspreet singh,<Media omitted>,Wednesday
12674,2020-06-24,7:40 PM,David Vazquez Data Analytics,Does it include de bokeh slider? 😛,Wednesday
12675,2020-06-24,7:40 PM,jaspreet singh,no idea,Wednesday
12676,2020-06-24,7:43 PM,Vasu DA Lanagara,Send me the Code if slider includes😂,Wednesday
12677,2020-06-24,8:08 PM,Kiran DA,Hi guys need php laravel developer and html d...,Wednesday

In [169]:
temp["Date"]

3       2019-09-04
4       2019-09-04
5       2019-09-04
6       2019-09-04
7       2019-09-05
           ...
12673   2020-06-24
12674   2020-06-24
12675   2020-06-24
12676   2020-06-24
12677   2020-06-24
Name: Date, Length: 11837, dtype: datetime64[ns]

In [170]:
temp["period"] = temp["Date"].astype(str) + temp["Time"]
temp["period"]

3         2019-09-04 8:21 PM
4         2019-09-04 8:22 PM
5         2019-09-04 8:22 PM
6         2019-09-04 8:27 PM
7        2019-09-05 12:34 PM
                 ...
12673     2020-06-24 7:19 PM
12674     2020-06-24 7:40 PM
12675     2020-06-24 7:40 PM
12676     2020-06-24 7:43 PM
12677     2020-06-24 8:08 PM
Name: period, Length: 11837, dtype: object

In [173]:
#new data frame with split value columns 
new = temp["period"].str.split(expand = True) 
  
#making separate first name column from new data frame 
temp["timestamp"]= new[0] 
  
#making separate last name column from new data frame 
temp["PmAm"]= new[1] 
  
#Dropping old Name columns 
#temp.drop(columns =["perio"], inplace = True) 
  
#df display 
temp

,Date,Time,Name,Messages,Weekdays,period,timestamp,PmAm
3,2019-09-04,8:21 PM,jaspreet singh,<Media omitted>,Wednesday,2019-09-04 8:21 PM,2019-09-04,8:21
4,2019-09-04,8:22 PM,jaspreet singh,Hardware required for this course is not that...,Wednesday,2019-09-04 8:22 PM,2019-09-04,8:22
5,2019-09-04,8:22 PM,jaspreet singh,May be our older system work for this course,Wednesday,2019-09-04 8:22 PM,2019-09-04,8:22
6,2019-09-04,8:27 PM,Dharun Canada DA,👀,Wednesday,2019-09-04 8:27 PM,2019-09-04,8:27
7,2019-09-05,12:34 PM,jaspreet singh,Did anyone know where this Maths Test will be...,Thursday,2019-09-05 12:34 PM,2019-09-05,12:34
...,...,...,...,...,...,...,...,...
12673,2020-06-24,7:19 PM,jaspreet singh,<Media omitted>,Wednesday,2020-06-24 7:19 PM,2020-06-24,7:19
12674,2020-06-24,7:40 PM,David Vazquez Data Analytics,Does it include de bokeh slider? 😛,Wednesday,2020-06-24 7:40 PM,2020-06-24,7:40
12675,2020-06-24,7:40 PM,jaspreet singh,no idea,Wednesday,2020-06-24 7:40 PM,2020-06-24,7:40
12676,2020-06-24,7:43 PM,Vasu DA Lanagara,Send me the Code if slider includes😂,Wednesday,2020-06-24 7:43 PM,2020-06-24,7:43
12677,2020-06-24,8:08 PM,Kiran DA,Hi guys need php laravel developer and html d...,Wednesday,2020-06-24 8:08 PM,2020-06-24,8:08

In [174]:
temp["timestamp"]

3        2019-09-04
4        2019-09-04
5        2019-09-04
6        2019-09-04
7        2019-09-05
            ...
12673    2020-06-24
12674    2020-06-24
12675    2020-06-24
12676    2020-06-24
12677    2020-06-24
Name: timestamp, Length: 11837, dtype: object

In [171]:
temp['newdate'] =  pd.to_datetime(temp['period'], format='%Y/%m/%d %H:%M:%p')

ValueError: time data '2019-09-04 8:21 PM ' does not match format '%Y/%m/%d %H:%M:%p' (match)

In [139]:
# new data frame with split value columns 
#new = data["Time"].str.split(expand = True) 
  
# making separate first name column from new data frame 
#data["Hours"]= new[0] 
  
# making separate last name column from new data frame 
#data["PmAm"]= new[1] 
  
# Dropping old Name columns 
#data.drop(columns =["eveOrMor"], inplace = True) 
  
# df display 
#data

,Date,Time,Name,Messages,Weekdays,Hours,PmAm
3,2019-09-04,8:21 PM,jaspreet singh,<Media omitted>,Wednesday,8:21,PM
4,2019-09-04,8:22 PM,jaspreet singh,Hardware required for this course is not that...,Wednesday,8:22,PM
5,2019-09-04,8:22 PM,jaspreet singh,May be our older system work for this course,Wednesday,8:22,PM
6,2019-09-04,8:27 PM,Dharun Canada DA,👀,Wednesday,8:27,PM
7,2019-09-05,12:34 PM,jaspreet singh,Did anyone know where this Maths Test will be...,Thursday,12:34,PM
...,...,...,...,...,...,...,...
12673,2020-06-24,7:19 PM,jaspreet singh,<Media omitted>,Wednesday,7:19,PM
12674,2020-06-24,7:40 PM,David Vazquez Data Analytics,Does it include de bokeh slider? 😛,Wednesday,7:40,PM
12675,2020-06-24,7:40 PM,jaspreet singh,no idea,Wednesday,7:40,PM
12676,2020-06-24,7:43 PM,Vasu DA Lanagara,Send me the Code if slider includes😂,Wednesday,7:43,PM
12677,2020-06-24,8:08 PM,Kiran DA,Hi guys need php laravel developer and html d...,Wednesday,8:08,PM

In [140]:
data['Hours'] =  pd.to_datetime(data['Hours'], format='%H:%M')

In [118]:
data['Hours'] = pd.to_datetime(data.Hours)

In [176]:
temp =data

temp

In [177]:
temp

,Date,Time,Name,Messages,Weekdays,period,timestamp,PmAm
3,2019-09-04,8:21 PM,jaspreet singh,<Media omitted>,Wednesday,2019-09-04 8:21 PM,2019-09-04,8:21
4,2019-09-04,8:22 PM,jaspreet singh,Hardware required for this course is not that...,Wednesday,2019-09-04 8:22 PM,2019-09-04,8:22
5,2019-09-04,8:22 PM,jaspreet singh,May be our older system work for this course,Wednesday,2019-09-04 8:22 PM,2019-09-04,8:22
6,2019-09-04,8:27 PM,Dharun Canada DA,👀,Wednesday,2019-09-04 8:27 PM,2019-09-04,8:27
7,2019-09-05,12:34 PM,jaspreet singh,Did anyone know where this Maths Test will be...,Thursday,2019-09-05 12:34 PM,2019-09-05,12:34
...,...,...,...,...,...,...,...,...
12673,2020-06-24,7:19 PM,jaspreet singh,<Media omitted>,Wednesday,2020-06-24 7:19 PM,2020-06-24,7:19
12674,2020-06-24,7:40 PM,David Vazquez Data Analytics,Does it include de bokeh slider? 😛,Wednesday,2020-06-24 7:40 PM,2020-06-24,7:40
12675,2020-06-24,7:40 PM,jaspreet singh,no idea,Wednesday,2020-06-24 7:40 PM,2020-06-24,7:40
12676,2020-06-24,7:43 PM,Vasu DA Lanagara,Send me the Code if slider includes😂,Wednesday,2020-06-24 7:43 PM,2020-06-24,7:43
12677,2020-06-24,8:08 PM,Kiran DA,Hi guys need php laravel developer and html d...,Wednesday,2020-06-24 8:08 PM,2020-06-24,8:08

In [ ]:
lineplot()

In [148]:
temp["period"] = df["Year"] + df["quarter"]

TypeError: combine() argument 2 must be datetime.time, not Timestamp

In [147]:
from datetime import datetime, timedelta
temp['Hours'] = pd.to_timedelta(temp['Hours'].astype(str)) + pd.to_timedelta('12:00')

ValueError: only leading negative signs are allowed

In [149]:
print(temp["Hours"])

3       1900-01-01 08:21:00
4       1900-01-01 08:22:00
5       1900-01-01 08:22:00
6       1900-01-01 08:27:00
7       1900-01-01 12:34:00
                ...
12673   1900-01-01 07:19:00
12674   1900-01-01 07:40:00
12675   1900-01-01 07:40:00
12676   1900-01-01 07:43:00
12677   1900-01-01 08:08:00
Name: Hours, Length: 11837, dtype: datetime64[ns]